 # Copyright (c) 2020 Allan Mobley. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

trigger:
  - master
  
name: Publish to Nuget

pool:
  vmImage: ubuntu-latest

variables:
  configuration: 'Release'
  projectPath: 'src/Azure.Functions.CosmosHttpTrigger.Extension.csproj'

stages:

  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: build
              configuration: --configuration $(configuration)
              projects: $(projectPath)

  - stage: Pack
    displayName: Pack Stage
    dependsOn: Build
    jobs:
      - job: Pack
        displayName: Pack
        steps:
          - task: DotNetCoreCLI@2
            displayName: Pack
            inputs:
              command: pack
              arguments: --configuration $(configuration)
              packagesToPack: $(projectPath)
              nobuild: true

  - stage: Push
    displayName: Push Stage
    dependsOn: Pack
    jobs:
      - job: Push
        displayName: Push
        steps:
          - task: NuGetCommand@2
            displayName: Push
            inputs:
              command: push
              packagesToPush: src/bin/Release/*.nupkg
              nuGetFeedType: external
              publishFeedCredentials: Mobsites Nuget
              allowPackageConflicts: true

