# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  configuration: 'Release'
  projectPath: 'src/Azure.Functions.CosmosHttpTrigger.Extension.csproj'

steps:
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build
      configuration: $(configuration)
      projects: $(projectPath)

  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: pack
      configuration: $(configuration)
      packagesToPack: $(projectPath)
      nobuild: true
  
  - task: NuGetCommand@2
    displayName: 'NuGet push'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'Mobsites Nuget'