 # Copyright (c) 2020 Allan Mobley. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.

trigger:
  - master
  
name: Publish to Nuget

pool:
  vmImage: ubuntu-latest

variables:
  configuration: 'Release'
  projectPath: 'src/Azure.Functions.CosmosHttpTrigger.Extension.csproj'

stages:

  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: build
              configuration: $(configuration)
              projects: $(projectPath)

  - stage: Publish
    displayName: Publish Stage
    dependsOn: Build
    jobs:
      - job: Publish
        displayName: Publish
        steps:
          - task: NuGetCommand@2
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
              nuGetFeedType: 'external'
              publishFeedCredentials: 'Mobsites Nuget'

